config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'courses#index'
  get 'tags', to: 'application#tags'
  post 'search', to: 'courses#search'
  resources :courses do
    resources :course_items, path: 'items', except: [:index, :show] do
      member do
        put 'learn'
        put 'unlearn'
      end
    end
    collection do
      get 'own'
      get 'learning'
      get 'filter/:tag' , to: 'courses#filter', as: 'filter'
      get 'popular'
      get 'latest'
    end
    member do
      put 'enroll'
      put 'like'
      put 'unlike'
      get 'fork'
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :popular, :latest, :filter, :search]
  before_action :find_course, only: [:edit, :update, :destroy, :enroll, :like, :unlike, :fork]
  before_action :ensure_user_access, only: [:edit, :update, :destroy]

  def index
    @title = 'Latest courses on CourseHub'
    @courses = Course.all
  end

  def show
    @course = Course.includes(:course_progresses, :course_items).find(params[:id])
    if user_signed_in?
      @progress = CourseProgress.
        where(course_id: @course.id, user_id: current_user.id).first
    end
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      @course.tags = course_tags
      flash[:notice] = 'New course was successfully created'
      redirect_to courses_path
    else
      render :new
    end
  end

  def fork
    course = @course.fork(current_user.id)
    redirect_to course_path(course)
  end

  def edit
  end

  def update
    if @course.update(course_params)
      @course.tags = course_tags
      flash[:notice] = 'Course was successfully updated'
      redirect_to course_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @course.delete
    redirect_to courses_path
  end

  def own
    @title = 'Your own courses'
    @courses = current_user.courses
    render :index
  end

  def learning
    @progresses = CourseProgress.includes(:course).where(user: current_user)
  end

  def popular
    @title = 'Most popular courses'
    @courses = (Course.all.sort_by { |x| x.likes.size }).reverse
    render :index
  end

  def latest
    @title = 'Latest courses'
    @courses = Course.order_by(:created_at => 'desc')
    render :index
  end

  def enroll
    current_user.enroll(@course)
    flash[:notice] = "You've successfully enrolled in this course"
    redirect_to course_path(@course)
  end

  def like
    @course.like(current_user.id)
    render json: {result: 'ok', likes: @course.likes.size}
  end

  def unlike
    @course.unlike(current_user.id)
    render json: {result: 'ok', likes: @course.likes.size}
  end

  def filter
    tag = Tag.where(name: params[:tag]).first
    @title = "Courses with tag #{tag.name}"
    @courses = tag && tag.courses || []
    render :index
  end

  def search
    @title = "Search for: #{params[:search]}"
    keywords = params[:search].strip.downcase.split(/\s+/)
    @courses = Course.all.select do |course| 
      keywords.find do 
        |keyword| course.name.downcase.include?(keyword) || course.description.include?(keyword)
      end
    end
    render :index
  end

  protected

  def course_params
    params.require(:course).permit(:name, :description).
      merge(user: current_user)
  end

  def course_tags
    params[:course][:tags_names].strip.split(',')
  end

  def ensure_user_access
    unless @course && @course.user_id == current_user.id
      flash[:alert] = 'You can not edit this course'
      redirect_to(:back)
    end
  end

  def find_course
    @course = Course.find(params[:id])
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enroll_button
    link_to 'Enroll in this course', enroll_course_path(@course), method: 'put', class: 'btn btn-primary'
  end

  def course_progress
    [@course.course_items.try(:size) || 0, @progress.try(:items).try(:size) || 0]
  end
end

app/views/courses/_course.html.slim
= form_for @course, html: {role: 'form'} do |f|
  = validation_errors @course, 'course'
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: 'E.g. "Ruby for beginners"'
  .form-group
    = f.label :tags
    = f.text_field :tags_names, class: 'form-control', placeholder: 'Comma separated, e.g. "ruby, ruby on rails"'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', rows: 5, placeholder: 'Describe your course'
  = f.submit nil, class: 'btn btn-success'

app/views/courses/_course_item_list_item.html.slim
/ %w(article book podcast screencast website)
- icon_class = case course_item.type \
    when 'article' then 'glyphicon-list-alt' \
    when 'book' then 'glyphicon-book' \
    when 'podcast' then 'glyphicon-headphones' \
    when 'screencast' then 'glyphicon-facetime-video' \
    when 'course' then 'glyphicon-globe' \
    when 'other' then 'glyphicon-asterisk' \
end

.course_item_list_item.row
  .course_item_list_item_checkbox.col-lg-1.col-md-1.col-sm-1.col-xs-1
    - if user_signed_in? && current_user.enrolled?(@course)
      - if @progress.try(:items).try(:include?, course_item.id)
        a.glyphicon.glyphicon-check.mark-as-unlearnt data-course=@course.id data-item=course_item.id
      - else
        a.glyphicon.glyphicon-unchecked.mark-as-learnt data-course=@course.id data-item=course_item.id
    - else
      a.glyphicon.glyphicon-unchecked data-toggle="modal" data-target="#enroll-first"
  .col-lg-11.col-md-11.col-sm-11.col-xs-11
    .course_item_list_item.row
      .col-lg-7.col-md-7.col-sm-6.col-xs-6
        = course_item.name
      .col-lg-2.col-md-2.col-sm-2.col-xs-2
        span.glyphicon.glyphicon-time
        span
          =<> number_to_human(course_item.duration)
          | hours
      .col-lg-3.col-md-3.col-sm-4.col-xs-4
        a.label.label-default href=course_item.url target="_blank"
          span class="glyphicon #{icon_class}"
          = " #{course_item.type}"

        - if(current_user && @course.user_id == current_user.id)
          span.author_options.dropdown
            span.glyphicon.glyphicon-cog data-toggle='dropdown' aria-haspopup='true' role='button' aria-expanded='false'
            .dropdown-menu.row role='menu'
              .col-lg-6.col-md-6.col-sm-6.col-xs-6
                = link_to 'Edit item', edit_course_course_item_path(@course, course_item), class: 'btn btn-warning btn-sm'
              .col-lg-6.col-md-6.col-sm-6.col-xs-6
                = link_to 'Delete', course_course_item_path(@course, course_item), method: 'delete', class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure? This action is UNREVERTABLE' }
          span style='clear:both'

app/views/courses/_course_list_item.html.slim
.col-lg-4.col-md-4.col-sm-4.col-xs-6
  .course_list_item
    h3 = link_to course.name, course_path(course)
    .course_stats.row
      .duration.col-lg-4.col-md-4.col-sm-4.col-xs-4
        span.glyphicon.glyphicon-time
        span
          =<> number_to_human(course.duration)
          | hours
      .likes.col-lg-3.col-md-3.col-sm-3.col-xs-3
        span.glyphicon.glyphicon-thumbs-up
        | &nbsp;
        span = course.likes.nil? ? 0 : course.likes.size
      .author.col-lg-5.col-md-5.col-sm-5.col-xs-5
        span.glyphicon.glyphicon-user
        | &nbsp;
        span = course.user.email.split('@').first
    - unless course.tags.empty?
      .course_tags
        span.glyphicon.glyphicon-tag
        - course.tags.each do |tag|
          a.label.label-success href='#{filter_courses_path(tag.name)}' = tag.name
    .desc
      - if course.description.length > 200
        = course.description.truncate(200)
        =< link_to 'read more', course_path(course)
      - else
        = course.description

app/views/courses/_learning_course_list_item.html.slim
- course = progress.course
.col-lg-4.col-md-4.col-sm-4.col-xs-6
  .learning_course_list_item
    h3 = link_to course.name, course_path(course)
    - if current_user && course.user_id == current_user.id
      span.label.label-primary Your course
    .course_stats.row
      .duration.col-lg-6.col-md-6.col-sm-12.col-xs-12
        span.glyphicon.glyphicon-time
        span
          =<> number_to_human(course.duration)
          | hours
      .likes.col-lg-6.col-md-6.col-sm-12.col-xs-12
        span.glyphicon.glyphicon-thumbs-up
        | &nbsp;
        span = course.likes.try(:size) || 0
    - unless course.tags.empty?
      .course_tags
        span.glyphicon.glyphicon-tag
        - course.tags.each do |tag|
          a.label.label-success href='#{filter_courses_path(tag.name)}' = tag.name
    .desc
      - if course.description.length > 200
        = course.description.truncate(200)
        =< link_to 'read more', course_path(course)
      - else
        = course.description
    .learning-progress
      - total = course.course_items.try(:size) || 0
      - learnt = progress.try(:items).try(:size) || 0
      h4 Your progress: #{learnt}/#{total}
      - unless total.zero?
        .progress
          - percents = [learnt.to_f / total * 100, 100].min
          .progress-bar role='progressbar' style="width: #{percents}%"

app/views/courses/edit.html.slim
= render 'course'

app/views/courses/index.html.slim
.row
  h1 = @title

.row.course_list
  - if @courses.empty?
    .alert.alert-warning No courses here..
  - else
    - for course in @courses
      = render 'courses/course_list_item', {course: course}

app/views/courses/learning.html.slim
.row
  h1 Courses you have enrolled

.row.course_list
  - if @progresses.empty?
    .alert.alert-warning Sorry. There are no available courses.
  - else
    - for progress in @progresses
      = render 'courses/learning_course_list_item', {progress: progress}

app/views/courses/new.html.slim
= render 'course'

app/views/courses/show.html.slim
.row
  .course_content.col-lg-9.col-md-9.col-sm-9.col-xs-9
    h1 = @course.name
    = twitter_button text: 'Check out this beautiful course!'
    hr
    - if current_user && @course.user_id != current_user.id
      = link_to 'Fork course', fork_course_path(@course), class: 'btn btn-info'
      hr
    - unless @course.tags.empty?
      .course_tags
        span.glyphicon.glyphicon-tag
        - @course.tags.each do |tag|
          a.label.label-success href="#{filter_courses_path(tag.name)}" = tag.name
    h2
      small = @course.description
    hr
    - if @course.course_items.empty?
      .alert.alert-warning Whoops. There are no items in this course.
    - else
      - for course_item in @course.course_items
        = render 'course_item_list_item', {course_item: course_item}

    - if current_user && @course.user_id == current_user.id
      hr
      h4 Author's actions
      .row
        .col-lg-3.col-md-3.col-sm-3.col-xs-3
          =  link_to 'Create new item', new_course_course_item_path(@course), class: 'btn btn-success'
        .col-lg-3.col-md-3.col-sm-3.col-xs-3
          span =  link_to 'Edit course info', edit_course_path(@course), class: 'btn btn-warning'
        .col-lg-3.col-md-3.col-sm-3.col-xs-3.col-lg-offset-3.col-md-offset-3.col-sm-offset-3.col-xs-offset-3
          span = link_to 'DELETE COURSE', course_path(@course), method: 'delete', class: 'btn btn-danger', data: { confirm: 'Are you sure? This action is UNREVERTABLE' }


  .user_progress.col-lg-3.col-md-3.col-sm-3.col-xs-3
    .course_stats.row
      .duration.col-lg-6.col-md-6.col-sm-12.col-xs-12
        span.glyphicon.glyphicon-time
        span
          =<> number_to_human(@course.duration)
          | hours
      .likes.col-lg-6.col-md-6.col-sm-12.col-xs-12
        - if current_user
          - liked = @course.like?(current_user.id)
          button class="like-button btn btn-default btn-xs #{'active' if liked}"
            span.glyphicon.glyphicon-thumbs-up
            span &nbsp;
            span.likes-value = @course.likes.nil? ? 0 : @course.likes.size
        - else
          span
            span.glyphicon.glyphicon-thumbs-up
            span &nbsp;
            span = @course.likes.nil? ? 0 : @course.likes.size
    .user_progress_stats.row
      .col-lg-12.col-md-12.col-sm-12.col-xs-12
        - if user_signed_in? && current_user.enrolled?(@course)
          - total, learnt = course_progress
          h3
            | Your progress:
            span.learnt< = learnt
            | /
            span.total =total
          - unless total.zero?
            .progress
              - percents = [learnt.to_f / total * 100, 100].min
              .progress-bar.percents role='progressbar' style="width: #{percents}%"
        - else
            = enroll_button

= modal_window('enroll-first', 'Information', \
    'To save your progress you must enroll in this course first', enroll_button)