config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'courses#index'
  get 'tags', to: 'application#tags'
  post 'search', to: 'courses#search'
  resources :courses do
    resources :course_items, path: 'items', except: [:index, :show] do
      member do
        put 'learn'
        put 'unlearn'
      end
    end
    collection do
      get 'own'
      get 'learning'
      get 'filter/:tag' , to: 'courses#filter', as: 'filter'
      get 'popular'
      get 'latest'
    end
    member do
      put 'enroll'
      put 'like'
      put 'unlike'
      get 'fork'
    end
  end
end

app/views/layouts/_footer.html.slim
footer.footer
  .container
    p.text-muted &copy; The Green Elephant 2014

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse role='navigation'
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#{root_path}" CourseHub

    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav

        li.dropdown
          = link_to '#', data: {toggle: 'dropdown'} do
            | Browse courses 
            span.caret
            ul.dropdown-menu
              li
                = link_to('Most popular', popular_courses_path)
              li
                = link_to('Latest', latest_courses_path)
              li.divider
              li
                = link_to('All tags', tags_path)

        - if user_signed_in?
          li
            = link_to('Learn dashboard', learning_courses_path)
          li
            = link_to('My courses', own_courses_path)

      - if user_signed_in?
        form#create-btn.navbar-form.navbar-left
          .form-group
            = link_to 'Create course', new_course_path, class: 'btn btn-success'

        div.navbar-right
          .navbar-text
            = current_user.email
            span &nbsp;
            = link_to('logout', destroy_user_session_path, method: 'delete', class: 'btn btn-danger btn-xs')
      - else
        form.navbar-form.navbar-right
          .form-group
            = link_to('Sign In', new_user_session_path, class: 'btn btn-success')
            | &nbsp;
            = link_to('Sign Up', new_user_registration_path, class: 'btn btn-warning')

      = form_tag("/search", class: 'navbar-form navbar-left', id: 'navbar-search') do
        .form-group
          = text_field_tag('search', nil, class: 'form-control', placeholder: 'Search')
        | &nbsp;
        = submit_tag("Search", class: 'btn btn-primary')

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width, initial-scale=1'

    title Coursehub

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css'
    script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js'
    = csrf_meta_tags

body
  = render 'layouts/header'
  .container.application
    = render 'shared/flashes'
    = yield
  = render 'layouts/footer'